[workspace]
resolver = "2"
members = [
    "tachys-sym",
    "tachys-document",
    "tachys-ui"
]

[workspace.dependencies]
internment = { version = "0.8", features = ["arc"] }

[profile.release]
lto = true

[profile.dev.package."*"]
opt-level = 3
