[package]
name = "tachys-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = { version = "0.30" }
softbuffer = "0.4"
tiny-skia = "0.11"

log = { version = "0.4", features = ["release_max_level_warn"] }
colog = "1.3"
